// App constants
export const AppConstants = {
    SELECT_DIR: 'SELECT_DIR',
    PLAY_TRACK: 'PLAY_TRACK',
    GET_DIR_AUDIO_METADATA: 'GET_DIR_AUDIO_MEADATA',
    DELETED_ITEMS_HAS_CHANGED: 'DELETED_ITEMS_HAS_CHANGED',
    COLLECTION_ITEM_HAS_CHANGED: 'COLLECTION_ITEMS_HAS_CHANGED',
    COLLECTION_ITEM: 'COLLECTION_ITEM',
    DELETE_ITEM: 'DELETED_ITEM',
};

